name: Style Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Download Checkstyle
        run: |
          wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.44/checkstyle-8.44-all.jar
          chmod +x checkstyle-8.44-all.jar

      - name: Run Checkstyle
        run: |
                    java -jar checkstyle-8.44-all.jar -c .github/checkstyle/google_checks.xml JohSmith_COMP228Lab1/src/

